version: 2.1
jobs:
  TruffleHog:
    docker:
      - image: gesellix/trufflehog
    steps:
      - checkout
      - run:
          name: Add Directory Variable
          command: |
            directory=$(pwd)
            echo $directory
      - run:
          name: Show Directory
          command: |
            ls -la
      - run:
          name: Run TruffleHog
          command: |
            trufflehog --regex --entropy=False /root/project > truffleResult
      - run:
          name: Read File
          command: |
            cat truffleResult
  semgrep-scan:
    parameters:
      repo_path:
        type: string
        default: /root/project
      default_branch:
        type: string
        default: main
    environment:
      SEMGREP_RULES: >- # more at semgrep.dev/explore
        p/security-audit
        p/secrets
        p/owasp-top-ten

      # Scan changed files in PRs, block on new issues only (existing issues ignored)
      SEMGREP_BASELINE_REF: << parameters.default_branch >>

    # == Optional settings in the `environment:` block

    # Instead of `SEMGREP_RULES:`, use rules set in Semgrep App.
    # Get your token from semgrep.dev/manage/settings.
    #   SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN
    #   SEMGREP_REPO_NAME: << parameters.repo_path >>
    #   SEMGREP_REPO_URL: << pipeline.project.git_url >>
    #   SEMGREP_BRANCH: << pipeline.git.branch >>

    # Never fail the build due to findings.
    # Instead, just collect findings for semgrep.dev/manage/findings
    #   SEMGREP_AUDIT_ON: unknown

    # Change job timeout (default is 1800 seconds; set to 0 to disable)
    #   SEMGREP_TIMEOUT: 300

    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: "Semgrep scan"
          command: semgrep ci    
workflows:
  main:
    jobs:
      - TruffleHog
      - semgrep-scan
